name: example
description: Example app for flutter_form_builder package
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  cupertino_icons: any
  flutter:
    sdk: flutter
  flutter_form_builder:
    path: ../
  form_builder_validators:
    git:
      url: https://github.com/BigPhilsnr/form_builder_validators.git
  flutter_localizations:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

